<%@ Page Title="" Language="C#" MasterPageFile="~/HomePage.master" AutoEventWireup="true" CodeFile="UserBookingInfo.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div style="width: 918px; height: 888px"><center>
<br /><br />

<form method="post" action="">
<table>
<tr>
<th colspan="2" style="width: 266px; height: 9px;">
<h2>To See User Booking Information Please Press Ok Button...</h2>
</th>
</tr>
<tr>
<td>
<asp:Button ID="Button1" runat="server" Text="Booking Info" Font-Bold="True" Font-Size="12pt" 
        Width="75px" onclick="Button1_Click"></asp:Button>
    <asp:CheckBox ID="ch1" runat="server" Visible="False" />
    <asp:Button ID="btnloginInfo" runat="server" Font-Bold="True" 
        Text="LogIn Info" onclick="btnloginInfo_Click" />
&nbsp;
    <asp:Button ID="btnregisinfo" runat="server" Font-Bold="True" 
        Text="Registration Info" onclick="btnregisinfo_Click" />
</td>
</tr>
<tr>
<td>
<asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="Bid" DataSourceID="SqlDataSource1" Visible="False" 
        AllowPaging="True" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" >
        
    <Columns>
        <asp:BoundField DataField="Bid" HeaderText="Bid" InsertVisible="False" 
            ReadOnly="True" SortExpression="Bid" />
        <asp:BoundField DataField="Uid" HeaderText="Uid" SortExpression="Uid" />
        <asp:BoundField DataField="Movie_Name" HeaderText="Movie_Name" 
            SortExpression="Movie_Name" />
        <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
        <asp:BoundField DataField="Time" HeaderText="Time" SortExpression="Time" />
        <asp:BoundField DataField="User_Name" HeaderText="User_Name" 
            SortExpression="User_Name" />
        <asp:BoundField DataField="Total_Amt" HeaderText="Total_Amt" 
            SortExpression="Total_Amt" />
    </Columns>

</asp:GridView>


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionStringregis %>" 
        SelectCommand="SELECT * FROM [Booking1]"
         ConflictDetection="CompareAllValues" 
        DeleteCommand="DELETE FROM [Booking1] WHERE [Bid] = @original_Bid AND (([Uid] = @original_Uid) OR ([Uid] IS NULL AND @original_Uid IS NULL)) AND (([Movie_Name] = @original_Movie_Name) OR ([Movie_Name] IS NULL AND @original_Movie_Name IS NULL)) AND (([Date] = @original_Date) OR ([Date] IS NULL AND @original_Date IS NULL)) AND (([Time] = @original_Time) OR ([Time] IS NULL AND @original_Time IS NULL)) AND (([User_Name] = @original_User_Name) OR ([User_Name] IS NULL AND @original_User_Name IS NULL)) AND (([Total_Amt] = @original_Total_Amt) OR ([Total_Amt] IS NULL AND @original_Total_Amt IS NULL))" 
        InsertCommand="INSERT INTO [Booking1] ([Uid], [Movie_Name], [Date], [Time], [User_Name], [Total_Amt]) VALUES (@Uid, @Movie_Name, @Date, @Time, @User_Name)" 
        OldValuesParameterFormatString="original_{0}" 
        UpdateCommand="UPDATE [Booking1] SET [Movie_Name] = @Movie_Name, [Date] = @Date, [Time] = @Time, [User_Name] = @User_Name, [Total_Amt] = @Total_Amt WHERE [Bid] = @original_Bid AND (([Uid] = @original_Uid) OR ([Uid] IS NULL AND @original_Uid IS NULL)) AND (([Movie_Name] = @original_Movie_Name) OR ([Movie_Name] IS NULL AND @original_Movie_Name IS NULL)) AND (([Date] = @original_Date) OR ([Date] IS NULL AND @original_Date IS NULL)) AND (([Time] = @original_Time) OR ([Time] IS NULL AND @original_Time IS NULL)) AND (([User_Name] = @original_User_Name) OR ([User_Name] IS NULL AND @original_User_Name IS NULL)) AND (([Total_Amt] = @original_Total_Amt) OR ([Total_Amt] IS NULL AND @original_Total_Amt IS NULL))">
        <DeleteParameters>
        <asp:Parameter Name="original_Bid" Type="Int32" />
            <asp:Parameter Name="original_Uid" Type="Int32" />
            <asp:Parameter Name="original_Movie_Name" Type="String" />
            <asp:Parameter Name="original_Date" Type="String" />
            <asp:Parameter Name="original_Time" Type="String" />
            <asp:Parameter Name="original_User_Name" Type="String" />
            <asp:Parameter Name="original_Total_Amt" Type="String" />
        </DeleteParameters>
        <InsertParameters>
        <asp:Parameter Name="Uid" Type="Int32" />
            <asp:Parameter Name="Movie_Name" Type="String" />
            <asp:Parameter Name="Date" Type="String" />
            <asp:Parameter Name="Time" Type="String" />
            <asp:Parameter Name="User_Name" Type="String" />
            <asp:Parameter Name="Total_Amt" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Uid" Type="Int32" />
            <asp:Parameter Name="Movie_Name" Type="String" />
            <asp:Parameter Name="Date" Type="String" />
            <asp:Parameter Name="Time" Type="String" />
            <asp:Parameter Name="User_Name" Type="String" />
            <asp:Parameter Name="Total_Amt" Type="String" />

            <asp:Parameter Name="original_Uid" Type="Int32" />
            <asp:Parameter Name="original_Movie_Name" Type="String" />
            <asp:Parameter Name="original_Date" Type="String" />
            <asp:Parameter Name="original_Time" Type="String" />
            <asp:Parameter Name="original_User_Name" Type="String" />
            <asp:Parameter Name="original_Total_Amt" Type="String" />
           
        </UpdateParameters>

        
        </asp:SqlDataSource>

</td>
</tr>
<tr>
<td>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        DataSourceID="SqlDataSource2" Visible="False"  
        DataKeyNames="username"
        AllowPaging="True" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
        <Columns>
            <asp:BoundField DataField="username" HeaderText="username" 
                SortExpression="username" />
            <asp:BoundField DataField="password" HeaderText="password" 
                SortExpression="password" />
            <asp:BoundField DataField="time" HeaderText="time" SortExpression="time" />
        </Columns>
    </asp:GridView>

    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionStringregis %>" 
        SelectCommand="SELECT * FROM [Login_Details]"
         ConflictDetection="CompareAllValues" 
        DeleteCommand="DELETE FROM [Login_Details] WHERE [username] = @original_username AND (([username] = @original_username) OR ([username] IS NULL AND @original_username IS NULL)) AND (([password] = @original_password) OR ([password] IS NULL AND @original_password IS NULL)) AND(([time] = @original_time) OR ([time] IS NULL AND @original_time IS NULL))" 
        InsertCommand="INSERT INTO [Login_Details] ([username], [password], [time], VALUES (@username, @password, @time)" 
        OldValuesParameterFormatString="original_{0}" 
        UpdateCommand="UPDATE [Login_Details] SET [username] = @username, [password] = @password, [time] = @time, WHERE [username] = @original_username (([password] = @original_password) OR ([password] IS NULL AND @original_password IS NULL)) AND (([time] = @original_time) OR ([time] IS NULL AND @original_time IS NULL))">
        <DeleteParameters>
        <asp:Parameter Name="original_username" Type="String" />
            <asp:Parameter Name="original_password" Type="String" />
            <asp:Parameter Name="original_time" Type="String" />
           </DeleteParameters>
        <InsertParameters>
       
            <asp:Parameter Name="username" Type="String" />
            <asp:Parameter Name="password" Type="String" />
            <asp:Parameter Name="Time" Type="String" />
            </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="username" Type="String" />
            <asp:Parameter Name="password" Type="String" />
            <asp:Parameter Name="Time" Type="String" />
            
           <asp:Parameter Name="original_username" Type="String" />
            <asp:Parameter Name="original_password" Type="String" />
            <asp:Parameter Name="original_time" Type="String" />
         
        </UpdateParameters>
        </asp:SqlDataSource>
</td>
</tr>

<tr>
<td>
    <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" 
        DataKeyNames="Uid" DataSourceID="SqlDataSource3" Visible="False">
        <Columns>
            <asp:BoundField DataField="Uid" HeaderText="Uid" InsertVisible="False" 
                ReadOnly="True" SortExpression="Uid" />
            <asp:BoundField DataField="Full_Name" HeaderText="Full_Name" 
                SortExpression="Full_Name" />
            <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
            <asp:BoundField DataField="Gender" HeaderText="Gender" 
                SortExpression="Gender" />
            <asp:BoundField DataField="Mobail_No" HeaderText="Mobail_No" 
                SortExpression="Mobail_No" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="User_Name" HeaderText="User_Name" 
                SortExpression="User_Name" />
            <asp:BoundField DataField="Password" HeaderText="Password" 
                SortExpression="Password" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionStringregis %>" 
        SelectCommand="SELECT * FROM [Registration]"></asp:SqlDataSource>
</td>
</tr>
</table>
</form>
</center>
</div>
</asp:Content>

