<%@ Page Title="" Language="VB" MasterPageFile="~/HomePage.master" AutoEventWireup="false" CodeFile="UserRegisData.aspx.vb" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<center>
<fieldset>
<legend>USer Data</legend>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionStringregis %>" 
        SelectCommand="SELECT * FROM [Registration]" 
        ConflictDetection="CompareAllValues" 
        DeleteCommand="DELETE FROM [Registration] WHERE [Uid] = @original_Uid AND (([Full_Name] = @original_Full_Name) OR ([Full_Name] IS NULL AND @original_Full_Name IS NULL)) AND (([Age] = @original_Age) OR ([Age] IS NULL AND @original_Age IS NULL)) AND (([Gender] = @original_Gender) OR ([Gender] IS NULL AND @original_Gender IS NULL)) AND (([Mobail_No] = @original_Mobail_No) OR ([Mobail_No] IS NULL AND @original_Mobail_No IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([User_Name] = @original_User_Name) OR ([User_Name] IS NULL AND @original_User_Name IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL))" 
        InsertCommand="INSERT INTO [Registration] ([Full_Name], [Age], [Gender], [Mobail_No], [Email], [User_Name], [Password]) VALUES (@Full_Name, @Age, @Gender, @Mobail_No, @Email, @User_Name, @Password)" 
        OldValuesParameterFormatString="original_{0}" 
        UpdateCommand="UPDATE [Registration] SET [Full_Name] = @Full_Name, [Age] = @Age, [Gender] = @Gender, [Mobail_No] = @Mobail_No, [Email] = @Email, [User_Name] = @User_Name, [Password] = @Password WHERE [Uid] = @original_Uid AND (([Full_Name] = @original_Full_Name) OR ([Full_Name] IS NULL AND @original_Full_Name IS NULL)) AND (([Age] = @original_Age) OR ([Age] IS NULL AND @original_Age IS NULL)) AND (([Gender] = @original_Gender) OR ([Gender] IS NULL AND @original_Gender IS NULL)) AND (([Mobail_No] = @original_Mobail_No) OR ([Mobail_No] IS NULL AND @original_Mobail_No IS NULL)) AND (([Email] = @original_Email) OR ([Email] IS NULL AND @original_Email IS NULL)) AND (([User_Name] = @original_User_Name) OR ([User_Name] IS NULL AND @original_User_Name IS NULL)) AND (([Password] = @original_Password) OR ([Password] IS NULL AND @original_Password IS NULL))">
        <DeleteParameters>
            <asp:Parameter Name="original_Uid" Type="Int32" />
            <asp:Parameter Name="original_Full_Name" Type="String" />
            <asp:Parameter Name="original_Age" Type="String" />
            <asp:Parameter Name="original_Gender" Type="String" />
            <asp:Parameter Name="original_Mobail_No" Type="String" />
            <asp:Parameter Name="original_Email" Type="String" />
            <asp:Parameter Name="original_User_Name" Type="String" />
            <asp:Parameter Name="original_Password" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Full_Name" Type="String" />
            <asp:Parameter Name="Age" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="Mobail_No" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="User_Name" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Full_Name" Type="String" />
            <asp:Parameter Name="Age" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="Mobail_No" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="User_Name" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="original_Uid" Type="Int32" />
            <asp:Parameter Name="original_Full_Name" Type="String" />
            <asp:Parameter Name="original_Age" Type="String" />
            <asp:Parameter Name="original_Gender" Type="String" />
            <asp:Parameter Name="original_Mobail_No" Type="String" />
            <asp:Parameter Name="original_Email" Type="String" />
            <asp:Parameter Name="original_User_Name" Type="String" />
            <asp:Parameter Name="original_Password" Type="String" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
        DataKeyNames="Uid" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="Uid" HeaderText="Uid" InsertVisible="False" 
                ReadOnly="True" SortExpression="Uid" />
            <asp:BoundField DataField="Full_Name" HeaderText="Full_Name" 
                SortExpression="Full_Name" />
            <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
            <asp:BoundField DataField="Gender" HeaderText="Gender" 
                SortExpression="Gender" />
            <asp:BoundField DataField="Mobail_No" HeaderText="Mobail_No" 
                SortExpression="Mobail_No" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="User_Name" HeaderText="User_Name" 
                SortExpression="User_Name" />
            <asp:BoundField DataField="Password" HeaderText="Password" 
                SortExpression="Password" />
        </Columns>
    </asp:GridView>
</fieldset>
</center>
</asp:Content>

